export const PKG_PREFIX = '@google-translate-select'
export const PKG_NAME = 'google-translate-select'
export const PKG_CAMELCASE_NAME = 'GoogleTranslateSelect'
export const PKG_CAMELCASE_LOCAL_NAME = 'GoogleTranslateSelectLocale'
export const PKG_BRAND_NAME = 'GoogleTranslateSelect'
