# This workflow warns issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale

name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '30 7 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.SELF_TOKEN }}
          days-before-stale: 30
          days-before-close: -1
          operations-per-run: 300
          stale-issue-message: 'Marking issue as stale since there was no activity for 30 days'
          stale-pr-message: 'Marking pull request as stale since there was no activity for 30 days'
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
